# Generated by Django 4.1.5 on 2024-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='fifth_content',
            field=models.CharField(max_length=256, verbose_name='fifth_content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='fourth_content',
            field=models.CharField(max_length=256, verbose_name='fourth_content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='second_content',
            field=models.CharField(max_length=256, verbose_name='second_content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='sixth_content',
            field=models.CharField(max_length=256, verbose_name='sixth_content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='third_content',
            field=models.CharField(max_length=256, verbose_name='third_content'),
        ),
    ]
