# Generated by Django 4.1.5 on 2024-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcontact',
            name='chart_from',
            field=models.TimeField(verbose_name='chart_from'),
        ),
        migrations.AlterField(
            model_name='ourcontact',
            name='chart_till',
            field=models.TimeField(verbose_name='chart_till'),
        ),
    ]
