# Generated by Django 4.1.5 on 2024-03-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
            ],
            options={
                'verbose_name': 'statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
