# Generated by Django 4.1.5 on 2024-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_first_images/', verbose_name='first_image')),
                ('second_image', models.ImageField(upload_to='gallery_second_images/', verbose_name='second_image')),
                ('third_image', models.ImageField(upload_to='gallery_third_images/', verbose_name='third_image')),
                ('fourth_image', models.ImageField(upload_to='gallery_fourth_images/', verbose_name='fourth_image')),
                ('fifth_image', models.ImageField(upload_to='gallery_fifth_images/', verbose_name='fifth_image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
