# Generated by Django 4.1.5 on 2024-03-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery image', 'verbose_name_plural': 'Gallery images'},
        ),
    ]
