# Generated by Django 4.1.5 on 2024-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='industry_images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'Industries',
            },
        ),
    ]
