# Generated by Django 4.1.5 on 2024-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='our_goals_images/', verbose_name='icon')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
            ],
            options={
                'verbose_name': 'our goal',
                'verbose_name_plural': 'Our goals',
            },
        ),
    ]
